### ISSUE TITLE
Add a separate rule for unused :keys bindings

### ISSUE THREAD

**Issue by danielcompton** [candid82/joker#240]
We sometimes will use something like `{:keys [id customer amount]}` to communicate to the reader that the map contains these keys, even if we don't use them in the function. These show up as warnings for `unused-bindings`. 

The standard guidance to fix this warning is to add an _ to the start of the name, but that doesn't make as much sense inside the `:keys` as you are referring to a real keyword. Would it make sense to split the warnings into `unused-bindings` and something like `unused-bindings-in-keys`?

**Comment by candid82** [comment]
Fixed by https://github.com/candid82/joker/commit/0ae176fee07f8a3e1c8f22880d8fde4ab618b08f

There is a new rule `:unused-keys` (defaults to true) which applies to `:keys`, `:strs`, and `:syms` bindings.

**Comment by borkdude** [comment]
@danielcompton I've asked for this feature before, but I wonder if this is still good practice for my own projects: Clojure will do unnecessary destructuring on each function call. I guess if your application is not performance critical, it doesn't matter, but for documentation something like spec might be better suited.

**Comment by danielcompton** [comment]
@borkdude that's a good point, I remember benchmarking destructuring in the past and being surprised how much slower it was than a `get`. In our case we are usually destructuring one or more keys, but not the full set, so we are paying the tax either way.

A quick benchmark I ran:

```
(def m {:x 1 :y 2 :z 3 :a 4 :b 5 :c 6 :d 7 :e 8})

(defn f [{:keys [x y z a b c]}]
  x)

(defn f2 [{:keys [x]}]
  x)

(defn f3 [m]
  (get m :x))

(criterium.core/bench (f m))
(criterium.core/bench (f2 m))
(criterium.core/bench (f3 m))
```

`f`: 83 ns
`f2`: 52 ns
`f3`: 6 ns

This is a good reminder though, and I think it used to be even slower in older versions of Clojure.

**Comment by borkdude** [comment]
@danielcompton A good compromise may be to use `:arglists` here:

```
user=> (defn f {:arglists '([{:keys [:x :y :z]}])} [obj])
#'user/f
user=> (doc f)
-------------------------
user/f
([{:keys [:x :y :z]}])
nil
```
You still get good editor support/documentation strings, but you don't pay the penalty when you don't need those destructured values.

**Comment by danielcompton** [comment]
That's an interesting idea, I hadn't considered that.

**Comment by hlship** [comment]
I prefer to define a spec for those kinds of things, even if we don't validate the input against the spec; unambiguous documentation.
